name: Deploy to Modal

on:
  push:
    branches: [master]
    paths:
      - chat-rag/**

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      MODAL_TOKEN_ID: ${{ secrets.MODAL_TOKEN_ID }}
      MODAL_TOKEN_SECRET: ${{ secrets.MODAL_TOKEN_SECRET }}
    defaults:
      run:
        working-directory: chat-rag
    steps:
      - uses: actions/checkout@v4

      - uses: astral-sh/setup-uv@v5

      - name: Update Modal secret
        run: >
          uvx modal secret create visa-rag-secrets
          MISTRAL_API_KEY=${{ secrets.MISTRAL_API_KEY }}
          GEMINI_API_KEY=${{ secrets.GEMINI_API_KEY }}
          LANGSMITH_TRACING=true
          LANGSMITH_PROJECT=visa-agent
          LANGSMITH_ENDPOINT=https://api.smith.langchain.com
          LANGSMITH_API_KEY=${{ secrets.LANGSMITH_API_KEY }}
          --force

      - name: Deploy to Modal
        run: uvx modal deploy deploy_modal.py
